all: clear clean compile

clear:
	@clear

clean:
	@rm -f makeFileSystem
	@rm -f fileSystemOper

compile:
	@g++ makeFileSystem.cpp -o makeFileSystem
	@g++ fileSystemOper.cpp -o fileSystemOper
